backend/src/main/java/com/cs490/group4/demo/controller/PatientController.java, backend/src/main/java/com/cs490/group4/demo/controller/PharmacyController.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientPharmacy.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientPharmacyRepository.java, backend/src/main/java/com/cs490/group4/demo/exception/GlobalExceptionHandler.java, backend/src/main/java/com/cs490/group4/demo/service/PatientPharmacyService.java, backend/src/main/java/com/cs490/group4/demo/service/PharmacyService.java, frontend/src/pages/Doctor/PendingAppointments.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Patient/SelectPharmacy.jsx, frontend/src/pages/SignupPage.jsx, frontend/src/utils/queryKeys.js
Going to change the signup logic to have the auth signup seperate
from the role-specific signup as described in the notion.
=> get preferred pharmacy in backend

backend/src/main/java/com/cs490/group4/demo/controller/RecipeController.java, backend/src/main/java/com/cs490/group4/demo/dao/Recipe.java, backend/src/main/java/com/cs490/group4/demo/dto/RecipeCreateDTO.java, frontend/package.json, frontend/src/pages/Recipes/RecipeCreate.jsx
Just need a way to upload to the media bucket and get the urls.
image sent as File to backend,
RecipeCreateDTO uses MultipartDTO to consume this
Recipe object has img_uri
=> add image to recipe in frontend

backend/src/main/java/com/cs490/group4/demo/config/MockDataConfig.java, backend/src/main/java/com/cs490/group4/demo/config/MockRecipe.java, backend/src/main/java/com/cs490/group4/demo/controller/RecipeController.java, backend/src/main/java/com/cs490/group4/demo/dao/RecipeIngredientRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/RecipeOwnerRepository.java, backend/src/main/java/com/cs490/group4/demo/dto/IngredientCreateRequestDTO.java, backend/src/main/java/com/cs490/group4/demo/service/CloudStorageService.java, backend/src/main/java/com/cs490/group4/demo/service/RecipeService.java, backend/src/main/resources/application.properties, frontend/src/pages/Recipes/RecipeCreate.jsx, frontend/src/pages/Recipes/Recipes.jsx
adding image to recipes
add deleting images to image service
creating service method for deleting recipes
=> Recipe image integration

backend/src/main/java/com/cs490/group4/demo/config/MockDataConfig.java, backend/src/main/java/com/cs490/group4/demo/controller/ChosenDoctorController.java, backend/src/main/java/com/cs490/group4/demo/controller/MealPlanController.java, backend/src/main/java/com/cs490/group4/demo/dao/ChosenDoctor.java, backend/src/main/java/com/cs490/group4/demo/dao/ChosenDoctorRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/MealPlan.java, backend/src/main/java/com/cs490/group4/demo/dao/MealPlanRepository.java, backend/src/main/java/com/cs490/group4/demo/dto/MealPlanCreateRequest.java, backend/src/main/java/com/cs490/group4/demo/dto/MealPlanCreateRequestDTO.java, backend/src/main/java/com/cs490/group4/demo/service/ChosenDoctorService.java, backend/src/main/java/com/cs490/group4/demo/service/MealPlanService.java, backend/src/main/resources/application.properties, frontend/src/NavBar.jsx, frontend/src/main.jsx, frontend/src/pages/Doctor/DoctorDashboard.jsx, frontend/src/pages/Doctor/DoctorPatients.jsx, frontend/src/pages/Doctor/DoctorQuickActions.jsx, frontend/src/pages/Doctor/Patients/SearchPatients.jsx, frontend/src/pages/Patient/AllDoctors.jsx, frontend/src/pages/Patient/MealPlansWidget.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Recipes/AssignMealPlan.jsx, frontend/src/pages/Recipes/RecipeCard.jsx, frontend/src/pages/Recipes/ViewMealPlans.jsx, frontend/src/utils/queryKeys.js
Patient picks doctor through appointment
Doctor can create and assign meal plans
patient can view meal plans
UI Changes to doctor and patient dashboard
Patient can see their chosen doctor
Doctor can see their chosen patients
=> Meal plans

backend/src/main/java/com/cs490/group4/demo/dao/PrescriptionBill.java, backend/src/main/java/com/cs490/group4/demo/dto/AppointmentDTO.java, backend/src/main/java/com/cs490/group4/demo/service/AppointmentService.java, backend/src/main/java/com/cs490/group4/demo/service/PrescriptionService.java, backend/src/main/java/com/cs490/group4/demo/service/RecipeCommentService.java, backend/src/test/java/com/cs490/group4/demo/service/AllergiesServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/AppointmentServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/ChosenDoctorServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/DailySurveyServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/DoctorServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/DrugServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/FavoriteFoodServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/MealPlanServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/MessageServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/PatientPharmacyServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/PatientServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/PharmacyServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/PrescriptionServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/RecipeCommentServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/RecipeIngredientServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/RecipeServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/WeeklySurveyServiceTest.java, backend/src/test/java/com/cs490/group4/demo/service/authentication/AuthenticationServiceTest.java
to run tests (in intellij IDEA ):
right click test/java -> More Run/Debug -> Run with Coverage
=> Service testing

frontend/src/main.jsx, frontend/src/pages/Doctor/Appointments/ConfirmedAppointments.jsx, frontend/src/pages/MessageRoom/MessageRoomPage.jsx, frontend/src/pages/Patient/PatientDashboard.jsx
=> get other user in message room

frontend/src/pages/Doctor/AssignRx.jsx
Updated the dynamic retrieval of pharmacyId upon changing patients. Submit button still doesn't work.
=> Doctor assign patient prescriptions- UPDATED

backend/src/main/java/com/cs490/group4/demo/controller/AppointmentController.java, backend/src/main/java/com/cs490/group4/demo/service/AppointmentService.java, backend/src/main/java/com/cs490/group4/demo/service/ChosenDoctorService.java, frontend/src/pages/Doctor/Appointments/CancelledAppointments.jsx, frontend/src/pages/Doctor/DoctorDashboard.jsx, frontend/src/pages/MessageRoom/MessageRoomPage.jsx, frontend/src/pages/Patient/AllDoctors.jsx, frontend/src/pages/Patient/MealPlansWidget.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Patient/PatientSurvey.jsx, frontend/src/pages/Patient/PendingAppointments.jsx, frontend/src/utils/queryKeys.js
patient can cancel confirmed appointments
When doctor is in chatroom, when polling for status also checks if the appointment has been cancelled.
=> cancel appointment, minor ui updates

backend/src/main/java/com/cs490/group4/demo/config/MockDataConfig.java, backend/src/main/java/com/cs490/group4/demo/config/MockSymptom.java, backend/src/main/java/com/cs490/group4/demo/controller/PatientSymptomsController.java, backend/src/main/java/com/cs490/group4/demo/controller/SymptomController.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientSymptoms.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientSymptomsRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/Symptom.java, backend/src/main/java/com/cs490/group4/demo/dao/SymptomRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/SymptomType.java, backend/src/main/java/com/cs490/group4/demo/dto/PatientSymptomCreateRequestDTO.java, backend/src/main/java/com/cs490/group4/demo/service/PatientSymptomsService.java, backend/src/main/java/com/cs490/group4/demo/service/SymptomService.java, frontend/src/NavBar.jsx, frontend/src/main.jsx, frontend/src/pages/Doctor/CompleteDoctorProfile.jsx, frontend/src/pages/Doctor/DoctorDashboard.jsx, frontend/src/pages/Doctor/DoctorPatients.jsx, frontend/src/pages/Doctor/DoctorQuickActions.jsx, frontend/src/pages/Patient/CompletePatientProfile.jsx, frontend/src/pages/Patient/CompletePatientSymptoms.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Patient/PatientQuickActions.jsx, frontend/src/pages/Patient/PatientSurvey.jsx, frontend/src/pages/Patient/PatientSymptoms.jsx, frontend/src/pages/Pharmacy/CompletePharmacyProfile.jsx, frontend/src/utils/queryKeys.js
-hippa in sign up
-Patient can fill out their symptoms
automatically routes to this after signup, and they can edit it afterwards
-doctors can view patient symptoms
bug fix- Routes to dashboard when trying to go back to complete-profile after a profile has already been completed.
minor ui changes
=> Patient symptoms and hippa

backend/src/main/java/com/cs490/group4/demo/config/MockDataConfig.java, backend/src/main/java/com/cs490/group4/demo/config/MockDoctor.java, backend/src/main/java/com/cs490/group4/demo/controller/DoctorController.java, backend/src/main/java/com/cs490/group4/demo/dao/Doctor.java, backend/src/main/java/com/cs490/group4/demo/service/DoctorService.java, backend/src/test/java/com/cs490/group4/demo/service/DoctorServiceTest.java, frontend/src/pages/Doctor/CompleteDoctorProfile.jsx, frontend/src/pages/Patient/CompletePatientProfile.jsx, frontend/src/pages/Pharmacy/CompletePharmacyProfile.jsx
Completed user signup input validations. Modified doctor entity to use String instead of Long for LicenceNum. Manually tested and ready to merge.
=> User input validation

backend/src/main/java/com/cs490/group4/demo/config/MockPatientPharmacy.java, backend/src/main/java/com/cs490/group4/demo/controller/PatientPharmacyController.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientPharmacyRepository.java, backend/src/main/java/com/cs490/group4/demo/service/ChosenDoctorService.java, backend/src/main/java/com/cs490/group4/demo/service/PatientPharmacyService.java, frontend/src/main.jsx, frontend/src/pages/Patient/PatientChosenDoctor.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Patient/PatientEditPreferredPharmacy.jsx, frontend/src/pages/Patient/PatientQuickActions.jsx, frontend/src/pages/Patient/Pharmacy/PatientPharmacy.jsx, frontend/src/utils/queryKeys.js
patient can change preferred pharmacy
invalidating query when firing doctor to avoid refreshing
=> Change preferred pharmacy

frontend/src/pages/Pharmacy/CompletePharmacyProfile.jsx
Fixed CompletePharmacyProfile.jsx
=> Minor fix. Import useContext fixed.

backend/src/main/java/com/cs490/group4/demo/config/MockCreditCard.java, backend/src/main/java/com/cs490/group4/demo/config/MockDataConfig.java, backend/src/main/java/com/cs490/group4/demo/controller/CreditCardController.java, backend/src/main/java/com/cs490/group4/demo/dao/CreditCard.java, backend/src/main/java/com/cs490/group4/demo/dao/CreditCardRepository.java, backend/src/main/java/com/cs490/group4/demo/dto/CreditCardRequestDTO.java, backend/src/main/java/com/cs490/group4/demo/dto/CreditCardResponseDTO.java, backend/src/main/java/com/cs490/group4/demo/service/CreditCardService.java, frontend/src/main.jsx, frontend/src/pages/Patient/CompletePatientProfile.jsx, frontend/src/pages/Patient/PatientInputCreditCard.jsx
Patient can add credit card in /patient/add_payment
To get patient credit cards: GET /credit-cards?patientId=
empty array if patient has no credit cards
=> Credit cards

backend/src/main/java/com/cs490/group4/demo/dao/Appointment.java, frontend/src/pages/Doctor/Appointments/ConfirmedAppointments.jsx, frontend/src/pages/Doctor/Appointments/PendingAppointments.jsx, frontend/src/pages/Doctor/DoctorDashboard.jsx, frontend/src/pages/MessageRoom/MessageRoomPage.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Patient/PendingAppointments.jsx
Doctors can no longer enter appointments that aren't started yet (appointment date being today)
Text in messages now visible in dark mode
=> ui changes

backend/src/main/java/com/cs490/group4/demo/config/MockDataConfig.java, backend/src/main/java/com/cs490/group4/demo/config/MockDrug.java, backend/src/main/java/com/cs490/group4/demo/dao/Drug.java, backend/src/main/java/com/cs490/group4/demo/dto/DrugDTO.java, backend/src/main/java/com/cs490/group4/demo/dto/PharmacyDrugDTO.java, backend/src/main/java/com/cs490/group4/demo/service/DrugService.java, backend/src/main/resources/application.properties, frontend/src/pages/Pharmacy/Bills.jsx, frontend/src/pages/Pharmacy/Patients.jsx, frontend/src/pages/Pharmacy/Pharmacydashboard.jsx, frontend/src/pages/Pharmacy/prescriptions.jsx
=> connecting backend and front

backend/src/main/java/com/cs490/group4/demo/controller/MealPlanController.java, backend/src/main/java/com/cs490/group4/demo/dto/MealPlanCaloriesDTO.java, backend/src/main/java/com/cs490/group4/demo/service/MealPlanService.java, frontend/src/pages/AppointmentCompletePage.jsx, frontend/src/pages/Patient/PatientSurvey.jsx
When patient is assigned a meal plan by a doctor, they can autofill it in the daily surveys.
=> autofill mealplan in daily survey

backend/src/main/java/com/cs490/group4/demo/controller/PatientPharmacyController.java, backend/src/main/java/com/cs490/group4/demo/controller/PharmacyController.java, backend/src/main/java/com/cs490/group4/demo/dao/DrugRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientPharmacyRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/PrescriptionBillRepository.java, backend/src/main/java/com/cs490/group4/demo/dao/PrescriptionRepository.java, backend/src/main/java/com/cs490/group4/demo/service/DrugService.java, backend/src/main/java/com/cs490/group4/demo/service/PatientPharmacyService.java, backend/src/main/java/com/cs490/group4/demo/service/PharmacyService.java, backend/src/main/java/com/cs490/group4/demo/service/PrescriptionService.java, backend/src/main/resources/application.properties, frontend/src/pages/Doctor/AssignRx.jsx, frontend/src/pages/Pharmacy/Bills.jsx, frontend/src/pages/Pharmacy/Pharmacydashboard.jsx, frontend/src/pages/Pharmacy/prescriptions.jsx
I added another feature to the pharmacy prescription page that allows pharmacists to add new medicines that are NOT already in the inventory but exist in the drugs table. At this point, this page should be renamed our pharmacy inventory control. This may be one additional feature for the 6 extras that we need. We can have our prescription fulfillment on the pharmacy dashboard.
=> More pharmacy fixes

backend/src/main/java/com/cs490/group4/demo/controller/PharmacyController.java, backend/src/main/java/com/cs490/group4/demo/controller/PrescriptionController.java, backend/src/main/java/com/cs490/group4/demo/service/PrescriptionService.java, frontend/src/NavBar.jsx, frontend/src/main.jsx, frontend/src/pages/Patient/PatientBills.jsx, frontend/src/pages/Patient/PaymentPortal.jsx
=> Patient payment portal

backend/src/main/java/com/cs490/group4/demo/controller/PatientAppointmentDataController.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientAppointmentData.java, backend/src/main/java/com/cs490/group4/demo/dao/PatientAppointmentDataRepository.java, backend/src/main/java/com/cs490/group4/demo/dto/PatientAppointmentDataCreateDTO.java, backend/src/main/java/com/cs490/group4/demo/service/PatientAppointmentDataService.java, frontend/src/main.jsx, frontend/src/pages/Doctor/DoctorPatients.jsx, frontend/src/pages/MessageRoom/MessageRoomPage.jsx, frontend/src/pages/Patient/AllPatientMetrics.jsx, frontend/src/pages/Patient/PatientAddAppointmentData.jsx, frontend/src/pages/Patient/PatientAppointmentGraphs.jsx, frontend/src/pages/Patient/PatientDashboard.jsx, frontend/src/pages/Patient/PatientMetrics.jsx, frontend/src/pages/Patient/PatientQuickActions.jsx, frontend/src/pages/Patient/PatientSurvey.jsx
Patients fill out information health before appointments
Doctors and patients can view this information (this information is consolidated along with the info from daily and weekly surveys)
=> Patient appointment data

backend/.gitignore, backend/src/main/resources/application.properties, frontend/src/NavBar.jsx, frontend/src/auth/AuthProvider.jsx, frontend/src/main.jsx, frontend/src/pages/Doctor/AssignRx.jsx, frontend/src/pages/Patient/PatientBills.jsx, frontend/src/pages/Patient/PaymentPortal.jsx, frontend/src/pages/Pharmacy/Bills.jsx, frontend/src/pages/Pharmacy/CompletePharmacyProfile.jsx, frontend/src/pages/Pharmacy/Patients.jsx, frontend/src/pages/Pharmacy/PharmacyHistoryOverride.jsx, frontend/src/pages/Pharmacy/Pharmacydashboard.jsx, frontend/src/pages/Pharmacy/prescriptions.jsx
=> Final changes
